apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubetask
  template:
    metadata:
      labels:
        app: kubetask
    spec:
      containers:
        - name: kubetask
          image:siva2805/kubetask
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served by $(hostname)" >> /usr/local/apache2/htdocs/index.html && \
              httpd-foreground